language: nodejs

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t saurabhnemade/themoviedb-frontend-challenge .
  - docker push saurabhnemade/themoviedb-frontend-challenge