const HOME = {
    HOME_LOAD_DEFAULT : "HOME_LOAD_DEFAULT",
    HOME_LOAD_DEFAULT_SUCCESS: "HOME_LOAD_DEFAULT_SUCCESS",
    HOME_LOAD_DEFAULT_FAILURE: "HOME_LOAD_DEFAULT_FAILURE"
};

export default {
    HOME
};