const HOME = {
    HOME_LOAD_DEFAULT : "HOME_LOAD_DEFAULT",
    HOME_LOAD_DEFAULT_SUCCESS: "HOME_LOAD_DEFAULT_SUCCESS",
    HOME_LOAD_DEFAULT_FAILURE: "HOME_LOAD_DEFAULT_FAILURE",
    HOME_SET_PAGE_NUMBER: "HOME_SET_PAGE_NUMBER"
};

const TRENDING = {
    TRENDING_LOAD_DEFAULT : "TRENDING_LOAD_DEFAULT",
    TRENDING_LOAD_DEFAULT_SUCCESS: "TRENDING_LOAD_DEFAULT_SUCCESS",
    TRENDING_LOAD_DEFAULT_FAILURE: "TRENDING_LOAD_DEFAULT_FAILURE"
};

const POPULAR = {
    POPULAR_LOAD_DEFAULT : "POPULAR_LOAD_DEFAULT",
    POPULAR_LOAD_DEFAULT_SUCCESS: "POPULAR_LOAD_DEFAULT_SUCCESS",
    POPULAR_LOAD_DEFAULT_FAILURE: "POPULAR_LOAD_DEFAULT_FAILURE"
};

const SEARCH = {
    SEARCH_SET_TERM : "SEARCH_SET_TERM",
    SEARCH_LOAD_DEFAULT : "SEARCH_LOAD_DEFAULT",
    SEARCH_LOAD_DEFAULT_SUCCESS: "SEARCH_LOAD_DEFAULT_SUCCESS",
    SEARCH_LOAD_DEFAULT_FAILURE: "SEARCH_LOAD_DEFAULT_FAILURE"
};

const MOVIE_DETAIL = {
    MOVIE_DETAIL_SET_ID : "MOVIE_DETAIL_SET_ID",
    MOVIE_DETAIL_LOAD: "MOVIE_DETAIL_LOAD",
    MOVIE_DETAIL_LOAD_SUCCESS : "MOVIE_DETAIL_LOAD_SUCCESS",
    MOVIE_DETAIL_LOAD_FAILURE : "MOVIE_DETAIL_LOAD_FAILURE",
    MOVIE_CAST_LOAD: "MOVIE_CAST_LOAD",
    MOVIE_CAST_LOAD_SUCCESS : "MOVIE_CAST_LOAD_SUCCESS",
    MOVIE_CAST_LOAD_FAILURE : "MOVIE_CAST_LOAD_FAILURE",
    MOVIE_DETAIL_RESET : "MOVIE_DETAIL_RESET"
};

const CAST_DETAIL = {
    CAST_DETAIL_SET_ID : "CAST_DETAIL_SET_ID",
    CAST_DETAIL_LOAD: "CAST_DETAIL_LOAD",
    CAST_DETAIL_LOAD_SUCCESS : "CAST_DETAIL_LOAD_SUCCESS",
    CAST_DETAIL_LOAD_FAILURE : "CAST_DETAIL_LOAD_FAILURE",
    CAST_DETAIL_RESET: "CAST_DETAIL_RESET"
};

export default {
    HOME,
    TRENDING,
    POPULAR,
    SEARCH,
    MOVIE_DETAIL,
    CAST_DETAIL
};